# Robot Configuration Parameters
TrajectoryPlannerROS:
    acc_lim_x: 0.2
    acc_lim_y: 0.2
    acc_lim_theta: 0.8
    max_vel_x: 0.3
    min_vel_x: 0.1
    # max_vel_y: 0.3
    # min_vel_y: -0.3

    # max_rotational_vel: 0.3 # 1.2
    # min_rotational_vel: -0.3 # 1.2

    max_vel_theta: 0.3 # 1.2
    min_vel_theta: 0.1 # 1.2

    max_in_place_rotational_vel: 0.3
    min_in_place_rotational_vel: 0.1
    escape_vel: -0.1
    holonomic_robot: true

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.05

    # Forward Simulation Parameters
    sim_time: 1.1
    sim_granularity: 0.025
    vx_samples: 3
    vtheta_samples: 6

    # Trajectory Scoring Parameters
    goal_distance_bias: 1.0
    path_distance_bias: 0.6

    # path_distance_bias: 32.0
    # goal_distance_bias: 20.0

    occdist_scale: 0.02
    heading_lookahead: 0.325
    dwa: false

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.05

    # meter_scoring: true
