map_type: costmap
transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.3
# robot_radius: 0.3

footprint:
  [ [0.35, 0.31],
    [0.35, -0.31],
    [-0.35, -0.31],
    [-0.35, 0.31] ]

observation_sources: base_scan_observation_front
# laser_scan_observation_xtion
# base_scan_observation_back
#

base_scan_observation_front: {
    sensor_frame: base_scan_link,
    data_type: LaserScan,
    topic: base_scan,
    expected_update_rate: 0.5,
    marking: true,
    clearing: true,
    obstacle_range: 2.5,
    raytrance_range: 3,
}

base_scan_observation_back: {
    sensor_frame: base_scan_back_link,
    data_type: LaserScan,
    topic: base_scan_back,
    expected_update_rate: 0.2,
    marking: true,
    clearing: true,
}

# laser_scan_observation_xtion: {
#     sensor_frame: xtion_depth_optical,
#     data_type: PointCloud2,
#     topic: xtion/depth/points,
#     expected_update_rate: 0.2,
#     marking: true,
#     clearing: true,
#     max_obstacle_height: 2.5,
#     min_obstacle_height: 0.035,
  # }
