#Independent settings for the planner's costmap
global_costmap:
    # publish_voxel_map: true
    global_frame: map # map
    robot_base_frame: base_link # base_link
    update_frequency: 2.0 # 2.5
    publish_frequency: 10.0
    static_map: true # false
    rolling_window: true
    width: 30.0 # 100.0
    height: 30.0 # 100.0
    resolution: 0.05
    # origin_x: 0.0
    # origin_y: 0.0
